"""API keys, stored as SHA-256 hashes in SQLite.

Why SHA-256 and not bcrypt: these keys are generated by
`secrets.token_urlsafe(24)` -- 192 bits of entropy. There is no dictionary to
attack and no reuse to exploit, so a deliberately slow key-derivation function
buys latency and nothing else. bcrypt would be the right answer if a human
chose the password.

The honest caveat, stated rather than hidden: a lookup by hash is still a
database comparison, and that is where timing can leak. `compare_digest` below
guards the in-process comparison but not the SQL. Closing that properly means
comparing against every stored hash, or using a fixed-length blind index.
"""
import hashlib
import hmac
import os
import secrets
import sqlite3

from src.config import ADMIN_KEY_ENV, DB_PATH, admin_key


def _conn():
    return sqlite3.connect(DB_PATH)


def _ready():
    """Connect with the schema guaranteed to exist.

    Why: an auth check can run before startup -- FastAPI dependency resolution
    does not wait for `on_event` in every path -- and without the table the
    check raises sqlite3.OperationalError instead of returning "not
    authorised". A missing schema should mean 'no key is valid', never a 500.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """CREATE TABLE IF NOT EXISTS api_keys (
               key_id TEXT PRIMARY KEY, name TEXT, key_hash TEXT UNIQUE,
               spend_cap REAL DEFAULT 0, active INTEGER DEFAULT 1,
               created_at TEXT DEFAULT (datetime('now')))"""
    )
    return conn


def _hash(key: str) -> str:
    return hashlib.sha256(key.encode()).hexdigest()


def init():
    """Create the key table and make sure the admin key is present.

    The admin row is upserted, not inserted-or-ignored. With key_id as the
    primary key, an insert-or-ignore only ever wrote it once -- so a database
    seeded by an earlier run kept that run's generated key and every subsequent
    request returned 401, with nothing in the logs to explain why. The env var is
    authoritative when set, because it is the only way to know which key the
    operator intends to use.
    """
    with _conn() as c:
        c.execute(
            """CREATE TABLE IF NOT EXISTS api_keys (
                   key_id TEXT PRIMARY KEY,
                   name TEXT,
                   key_hash TEXT UNIQUE,
                   spend_cap REAL DEFAULT 0,
                   active INTEGER DEFAULT 1,
                   created_at TEXT DEFAULT (datetime('now'))
               )"""
        )
        c.execute(
            """INSERT INTO api_keys (key_id, name, key_hash)
               VALUES ('admin', 'admin (bootstrap)', ?)
               ON CONFLICT(key_id) DO UPDATE SET key_hash = excluded.key_hash""",
            (_hash(admin_key()),),
        )


def issue(name: str, spend_cap: float = 0.0) -> str:
    """Create a key and return the plaintext exactly once."""
    plain = "kk-" + secrets.token_urlsafe(24)
    key_id = "k_" + secrets.token_hex(6)
    with _conn() as c:
        c.execute(
            "INSERT INTO api_keys (key_id, name, key_hash, spend_cap) VALUES (?,?,?,?)",
            (key_id, name, _hash(plain), spend_cap),
        )
    return plain


def verify(plain: str):
    """Return the key_id if the key is valid, else None."""
    if not plain:
        return None
    digest = _hash(plain)
    with _ready() as c:
        row = c.execute(
            "SELECT key_id FROM api_keys WHERE key_hash = ?", (digest,)
        ).fetchone()
    if row:
        return row[0]
    hmac.compare_digest(digest, digest)   # equal work on a miss
    return None


def is_active(key_id: str) -> bool:
    with _ready() as c:
        row = c.execute("SELECT active FROM api_keys WHERE key_id=?", (key_id,)).fetchone()
    return bool(row and row[0])


def spend_cap(key_id: str) -> float:
    with _ready() as c:
        row = c.execute("SELECT spend_cap FROM api_keys WHERE key_id=?", (key_id,)).fetchone()
    return float(row[0]) if row else 0.0


def revoke(key_id: str) -> bool:
    """Deactivate a key. True only if a row actually changed.

    Uses cursor.rowcount, not connection.total_changes: the latter is
    cumulative across the whole connection, so it reports success for a key that
    was already revoked.
    """
    with _ready() as c:
        return c.execute(
            "UPDATE api_keys SET active=0 WHERE key_id=?", (key_id,)
        ).rowcount > 0


def all_keys() -> list:
    with _ready() as c:
        rows = c.execute(
            "SELECT key_id, name, spend_cap, active, created_at FROM api_keys"
            " ORDER BY created_at DESC"
        ).fetchall()
    return [{"key_id": r[0], "name": r[1], "spend_cap_usd": r[2],
             "active": bool(r[3]), "created_at": r[4]} for r in rows]


def bearer(header: str):
    """Extract and verify a `Bearer <key>` header."""
    if not header or not header.startswith("Bearer "):
        return None
    return verify(header[7:].strip())
